Add files via upload

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1,6 +1,13 @@
 #!/bin/bash
 # tell the os to invoke speciefied shell 
-# temp="tmp.$$"
+
+# CST1500 Coursework 2 
+
+# M00724948 - Sebastian Sokalski 
+
+# M00737687 - Sebastiaan Gastol
+
+# functions file
 
 # function message displays dialog infobox with parameters given when invoking the function 
 function message {
@@ -8,9 +15,9 @@ function message {
    }
 
 # function end, terminates execution of the progeam if user selected exit or pressed Esc button
-function end {
+	function end {
     if [ "$1" = "1" ] || [ "$1" = "255" ]; then  # check if variable matches exit code
-    	message "$2" 5 35 # display infobox using parameter passed to the function and use 5 as height and 35 as width
+    	message "$2" $3 $4 # display infobox using parameter passed to the function and use 5 as height and 35 as width
     	clear # clear the screen
     	rm -f $temp # remove temporary file
     exit # terminate the program
@@ -19,34 +26,35 @@ function end {
 
 # deletes the file
 function delete_file {
-     dialog --yesno "Are you sure you want to delete? \n $FILE" 7 50 #use yes no dialog box to confirm deletion
-         if  [ $? = 0 ]; then # use exit code to confirm deletion             
-            if [ ! -e "$1" ]; then  # if file doesn't exist use function message to notify user 
-                 message "File does not exist." 10 30
-            else
-                  rm -f $1 # otherwise delete file and display confirmation 
-                  message "$1 has been deleted succsssfully" 0 0 
-            fi
+    if [ ! -e "$1" ]; then  # if file doesn't exist use function message to notify user 
+         message "File does not exist." 5 24
+    else
+        dialog --yesno "Are you sure you want to delete? \n $FILE" 6 50 #use yes no dialog box to confirm deletion
+        if  [ $? = 0 ]; then # use exit code to confirm deletion    
+            rm -f $1 # otherwise delete file and display confirmation 
+            message "$1 has been deleted succsssfully." 0 0          
          else # if exit code !(0) display the message operation terminated
-              message "Operation has been aborted by the user" 5 43
-         fi
+              message "Operation has been aborted by the user." 5 44
+         fi 
+    fi
 } 
 
-
+# checks if selected path is a file
 function isFile {
-     dialog --inputbox "Enter path: " 5 40 "$(pwd)/" 2> $temp # display inputbox and save the value to temp file
+     dialog --inputbox "Enter path or press enter to stay in current directory: " \
+ 	5 60 "$(pwd)/" 2> $temp # display inputbox and save the value to temp file
      path=`cat $temp` # assign value stroed in temp file to variable path
      # store path selected in dialogbox in varialbe FILE
      FILE=$(dialog --title "Delete a file" --stdout --title \
      "Please choose a file to delete" --fselect "$path" 20 100)
      if [ $? = 0 ]; then # if exit code = 0 
-         if [ -d "$FILE" ]; then # checks if path is directory
-              message "This path is not a file" 5 30  # if it is directory display error message
+         if [ -d "$FILE" ]; then # check if path is directory
+              message "This path is not a file." 5 30  # if it is directory display error message
          else # if it isn't invoke function delete file 
               delete_file $FILE
          fi
      else # display if cancelled pressed in fselect
-         message "Operation has been aborted by the user" 5 53
+         message "Operation has been aborted by the user." 5 44
      fi
 }
 
diff --git a/systemInfo b/systemInfo
--- a/systemInfo
+++ b/systemInfo
@@ -1,5 +1,12 @@
 #!/bin/bash
 # tell the os to invoke speciefied shell 
+
+# CST1500 Coursework 2 
+
+# M00724948 - Sebastian Sokalski 
+
+# M00737687 - Sebastiaan Gastol
+
 # system info
 
 . functions  # import external function file 
@@ -7,16 +14,16 @@ temp="tmp.$$" # assign temporary file to variable temp, where $$ will be replace
 
 while true # start infinite while loop  which will display dialog menu  
     do
-        dialog --backtitle "Sytem Info" \
+        dialog --backtitle "System Info" \
                --cancel-label "Exit" \
-               --menu "Choose one of the options" 15 30 10 \
+               --menu "Choose one of the options: " 15 30 4 \
 	1 "Operating system type" \
 	2 "CPU" \
 	3 "Memory information" \
 	4 "Hard disk information" \
 			2>$temp # save the exit code to variable temp 
 
-	end $? "Returning to the main menu." # pass exit code to function end 
+	end $? "Returning to the main menu." 5 32 # pass exit code to function end 
 
 	# save the value from temprora file to variable answer 
     	answer=`cat $temp`
@@ -26,12 +33,12 @@ while true # start infinite while loop  which will display dialog menu
 	# lscpu - linux command which determines cpu type
 	# free -h  linux command which dermines the memory 
 	# df -h  linux commna which shows hdd info annd mounting point
-        # case useses message funcion which displays dialog infobox. Function take paramaters relevant
-	# linux command and height and width of the infobox
+        # case useses message funcion which displays dialog infobox. Function take paramaters:
+	# relevant linux command and height and width of the infobox
     	case $answer in
 	    "1") message "$(uname -a)" 6 80 ;;
 	    "2") message "$(lscpu)" 40 160 ;;
-	    "3") message "$(free -h) " 8 60  ;;
+	    "3") message "$(free -h) " 7 60  ;;
 	    "4") message "$(df -h)"  28 80;;
      	esac
     done
